#!/usr/bin/env node

try {
    var reporter = require('nodeunit').reporters.default;
} catch(e) {
    console.log("Unable to find nodeunit. Rectify.");
    process.exit();
}

process.chdir(__dirname);
reporter.run(['test']);

